language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script: 
  - pycodestyle .
  - flake8 .
  - python setup.py install
  - python setup.py test
after_success:
  - codecov